所有的异常类是从`java.lang.Exception`类继承的子类

https://www.runoob.com/java/java-exceptions.html

https://zhuanlan.zhihu.com/p/133917885?utm_source=qq&utm_medium=social&utm_oi=730805508943929344

<a href="https://imgchr.com/i/BpiV9P"><img src="https://s1.ax1x.com/2020/10/20/BpiV9P.jpg" alt="BpiV9P.jpg" border="0"></a>

### 抓获异常

使用try 和 catch关键字可以捕获异常

```java
try{
    //可能异常的代码
}catch(ExceptionName e1)
{
    //catch块包含要捕获异常类型的声明。如果发生的异常包含在catch块中，异常会被传递到该catch块中
}
```

```java
import java.io.*;
public class ExcepTest{
    public static void main(String args[]){
        try{
            int a[]=new int[2];
            System.out.println("Access element three:"+a[3]);//数组越界
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println("Exception thrown :"+e);
        }
        System.out.println("out of the block");
    }
}
```

### 多重捕获块

```java
try{

}catch(异常类型1 异常变量名){
    
}catch(异常类型2 ....){
    
}catch(异常类型3....){
    
}
//直到异常被捕获或通过所有的catch块
```

### throws/throw

当==一个方法==产生一个它不处理的异常时,那么就需要在该方法的头部声明这个异常，以便将其传递到方法的外部进行处理

==区别==

- throws用来声明==一个方法可能抛出的==所有异常信息==，而throw则是指定的一个具体的异常类型
- throws通常在方法声明处声明(方法类)可能抛出的异常信息，而在==方法(类)内部通过throw声明==一个具体的异常信息。
- throws不显示地捕获异常，由系统自动将所有捕获的异常信息抛给上级方法(调用者)；throw则需要用户自己捕获相关异常

```java
import java.io.FileInputStream;
import java.io.IOException;

public class Test04{
public void readFile() throws IOException{//定义时声明异常
    FileInputStream file = new FileInputStream("read.txt");
    
    int f;
    while((f = file.read())!=-1){
        System.out.println((char)f);
        f = file.read();
    }
    file.close();
}
    
    public static void main(String args[]){
        Throws t = new Test04();
        try{
            t.readFile();
        }catch(IOException e){
            System.out.println(e);
        }
    }
}
}
//也可以自定义throw new (异常,这里必须是Exception的子类,或者自己定义)(内容)来抛出异常
```



### 自定义异常

```java
public class MyException extends Exception{
    public MyException(){
        super();
    }
    public MyException(String str){
        super(str);
    }
}
//下一步
import java.util.InputMismatchException;
import java.util.Scanner;
public class Test07 {
    public static void main(String[] args) {
        int age;
        Scanner input = new Scanner(System.in);
        System.out.println("请输入您的年龄：");
        try {
            age = input.nextInt();    // 获取年龄
            if(age < 0) {
                throw new MyException("您输入的年龄为负数！输入有误！");
            } else if(age > 100) {
                throw new MyException("您输入的年龄大于100！输入有误！");//初始化MyException异常
            } else {
                System.out.println("您的年龄为："+age);
            }
        } catch(InputMismatchException e1) {//这两句才是捕获异常的语句
            System.out.println("输入的年龄不是数字！");
        } catch(MyException e2) {
            System.out.println(e2.getMessage());
        }
    }
}
```

























